name: C++ CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

    defaults:
      run:
        shell: bash

jobs:
  build:
    name: Build selog on ${{ matrix.os }} with ${{ matrix.compiler }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        compiler: [g++, clang++]
        include:
          - os: ubuntu-latest
            target: Linux

          - os: macos-latest
            target: Macos

          - os: windows-latest
            target: Windows

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Add msbuild to PATH
        if: ${{ matrix.os == 'windows-latest' }}
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Run make
        run: make CXX=${{ matrix.compiler }} FORCE_CXX=1

      - name: Run selog
        run: make run
